require('./segment-test');
require('./snake-test');
require('./food-test');
require('./render-test');
require('./user-input-test');
require('./game-test');
require('./num-test');
require('./scoreboard-test');
require('./menu-test');
